### ISSUE TITLE
Can't move the icon past a certain point on my screen.

### ISSUE THREAD

**Issue by BrushStrokesL** [MediaModMC/MediaMod#22]
**Describe the bug**
Can't move the icon of "now playing" past a point on my screen.

**To Reproduce**
1. /mm
2. Scale down from 1.0
3. Move it

**Expected behavior**
Able to move the icon anywhere?

**Screenshots**
[https://youtu.be/Ur3kTRGpF8Y](url)

**Operating System**
Windows

**Service causing this bug, if applicable**
N/A (Youtube)

**Comment by AmpTheDev** [comment]
Thanks for the report, I'll look into it.
