### ISSUE TITLE
Have to re log every time the game launches

### ISSUE THREAD

**Issue by Twenst** [MediaModMC/MediaMod#24]
first congratulations for this mod,
then, idk if it's supposed to work like that but if it isn't a bug maybe a thing that make you staying connected between minecraft sessions will be cool

edit: i'm a linux user, not very sure if it's changing something

**Comment by chachyyyy** [comment]
tokens aren't stored as of now

**Comment by chachyyyy** [comment]
you could try ask @AmpTheDev for an eta but as of now it isn't in

**Comment by AmpTheDev** [comment]
This was intended behaviour but is changed in version 1.1.0.
