### ISSUE TITLE
Could be a bug 

### ISSUE THREAD

**Issue by Ectalite** [MediaModMC/MediaMod#30]
**Describe the bug**
Player doesn't show up and console is spammed.

**To Reproduce**
1. Build the last github version
2. Start a new world

**Console**
`[18:29:48] [pool-9-thread-1/INFO] [STDERR]: [me.conorthedev.mediamod.media.spotify.SpotifyHandler:getCurrentTrack:201]: 	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)`

**Operating System**
Windows 10 
Minecraft 1.8.9 
Forge 11.15.1.1722

**Comment by AmpTheDev** [comment]
Thanks for reporting, but I can't reproduce this issue. Can you send the full log file? Also, what's the output of `git log -n 1` in the project directory?

**Comment by Ectalite** [comment]
git does not work as I downloaded it from github directly 
Full log here : https://paste.ee/p/qDvhD

**Comment by Ectalite** [comment]
Clonned it with git, rebuild it and got the same. 
`$ git log -n 1
commit a188d116cc5cf4b4a2fcf0dfe8ae068ae945ef91 (HEAD -> master, origin/master)
Author: Ectalite <Xaxa.hueber@gmail.com>
Date:   Sat Oct 5 18:10:54 2019 +0200

    :page_facing_up: Adding french translation to the mod (#29)

    * Create fr_FR.lang

    * Update fr_FR.lang
`

**Comment by AmpTheDev** [comment]
Confirmed it's a bug, but can't reproduce. I'll try to investigate more and fix it.

**Comment by Ectalite** [comment]
I built it with windows console and git bash as do not have IntelliJ IDEA

**Comment by AmpTheDev** [comment]
That shouldn't matter, but thanks for the extra information.

**Comment by AmpTheDev** [comment]
Successfully reproduced the issue in development environment, fixing now.
