### ISSUE TITLE
Translations bug

### ISSUE THREAD

**Issue by Ectalite** [MediaModMC/MediaMod#31]
**Describe the bug**
Translations aren't fully working

**To Reproduce**
1. Use last github build
2. Go in MediaMod gui

**Expected behavior**
Translations 

**Screenshots**
![image](https://user-images.githubusercontent.com/31344054/66259314-d7f59600-e7af-11e9-85e3-91d1f24256e1.png)
![image](https://user-images.githubusercontent.com/31344054/66259329-fb204580-e7af-11e9-9e97-44a876d59dc4.png)

**Service causing this bug, if applicable**
What service were you using when the bug occurred? (Spotify, YouTube, SoundCloud, etc.)

**Additional context**
As translations are not using the same space they exceed.

**Comment by ConorTheDev** [comment]
Working on this now, give me 5 - 10 minutes!

**Comment by ConorTheDev** [comment]
Fixed in 419b877ea589b378bf4b68b6df43e4a2a03f0573

**Comment by Ectalite** [comment]
![image](https://user-images.githubusercontent.com/31344054/66270781-9b7d7500-e857-11e9-9423-9fe881145bfd.png)
![image](https://user-images.githubusercontent.com/31344054/66270807-c667c900-e857-11e9-8825-cb04001b0520.png)
Do you know if there is a way to automaticaly modify the width of texts ?

**Comment by AmpTheDev** [comment]
There is, but that doesn't have high priority.

**Comment by Ectalite** [comment]
Ok, good work for the rest. It works very good !
