### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by Ectalite** [MediaModMC/MediaMod#32]
**Is your feature request related to a problem? Please describe.**
Progress bar is only progressing by 3 in 3 seconds

**Describe the solution you'd like**
It should progress more harmoniously.

**Describe alternatives you've considered**
Reduce the time it takes to refresh.

**Additional context**
It's doing that with soundcloud and youtube (did not test with other services)

**Comment by ConorTheDev** [comment]
This shouldn't be happening with @AmpTheDev's estimation implementation

**Comment by AmpTheDev** [comment]
Yeah, and I've tested it with SoundCloud and YouTube while implemented it. @ConorTheDev Maybe the browser extension in the chrome web store / firefox store is outdated? If it is, it'll always report the track as paused.

**Comment by ConorTheDev** [comment]
Ah yes, I'll file an update for it tonight

**Comment by ConorTheDev** [comment]
Closing as this will be fixed when I update the extension
