### ISSUE TITLE
MediaMod Gui Keybind

### ISSUE THREAD

**Issue by Ectalite** [MediaModMC/MediaMod#33]
**Is your feature request related to a problem? Please describe.**
Add a keybind to open the Gui

**Describe the solution you'd like**
Add a keybind in Controls 

**Describe alternatives you've considered**
Add a settings menu in options (like Shaders menu with optifine)

**Comment by ConorTheDev** [comment]
Adding tonight

**Comment by asbyth** [comment]
https://github.com/MediaModMC/MediaMod/commit/c38654e151ade2d8f068e3ab5fb488c15f8e636d did it :-)
