### ISSUE TITLE
Player not showing up

### ISSUE THREAD

**Issue by pinkulu** [MediaModMC/MediaMod#38]
**Describe the bug.**
if Spotify music isn't started before launching minecraft the player wont show up and cant be toggled on unless you restart your game with music already playing.(atleset i think that thats the issue)
**To Reproduce**
1. launche the minecraft without music playing already

**Expected behavior**
the player should show up anytime you start the music and it did so in v1.0 but it dosnt anymore.(this bug has been around since v1.1 realese but i frogot to report it/didnt know what caused it)

**Screenshots**
i dont have a screenshot but theres realy nothing to show all the setttings are how thay are suppose to be

**Operating System**
Windows 10

**Service causing this bug, if applicable**
Spotify

**Additional context**
If you have any other questions ask them.

**Comment by Ectalite** [comment]
I think it's not actually a bug, but it appears when you are hearing music

**Comment by MyerFire** [comment]
i experience the same problem
