### ISSUE TITLE
Song not showing up

### ISSUE THREAD

**Issue by Rixxrd** [MediaModMC/MediaMod#48]
After using it for a few days the player doesn't show while playing song. I tried to re-connect Spotify but nothing. I tried to reinstall but that did nothing.

**Comment by Rixxrd** [comment]
*Update* The media player wont even play songs from youtube now.

![Hnet com-image](https://user-images.githubusercontent.com/64436064/80413093-95c0ad00-88d7-11ea-9507-f855255326eb.gif)

**Comment by cbyrne** [comment]
We will release an update in the next while to move the service back to our servers. I apologize for any inconvenience caused.
