### ISSUE TITLE
ERROR: Failed to login to Spotify 

### ISSUE THREAD

**Issue by fireofdoomy** [MediaModMC/MediaMod#58]
ERROR: Failed to login to Spotify!
I keep trying to login to Spotify but the ERROR: Failed to login to Spotify! message keeps showing up. I tried restarting, moving the mod back in the mod folder but nothing works! Should I just wait for the next update or how do I fix it? Is it my that I have other mods? I'm using the MediaMod-1.2.4. 

1. Press M 
2. Click on Services 
3. Click "Login to Spotify" 

Login to Spotify 

What OS are you on? (Windows, macOS, Linux)
 Windows 

What service were you using when the bug occurred? (Spotify, YouTube, SoundCloud, etc.)
Spotify and Minecraft

**Comment by cbyrne** [comment]
Can you use the latest beta release? You can learn how to obtain it in [the releases channel of my discord](https://discord.gg/9r5SkvU)

**Comment by fireofdoomy** [comment]
> Can you use the latest beta release? You can learn how to obtain it in [the releases channel of my discord](https://discord.gg/9r5SkvU)

Ok I did install the latest beta release but I get the message  
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/util/text/ITextComponent

**Comment by cbyrne** [comment]
> > Can you use the latest beta release? You can learn how to obtain it in [the releases channel of my discord](https://discord.gg/9r5SkvU)
> 
> 
> 
> Ok I did install the latest beta release but I get the message  
> 
> The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
> 
> Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/util/text/ITextComponent
> 
> 

What version did you download and what version of minecraft are you launching? Can you send the full log in a hastebin?

**Comment by fireofdoomy** [comment]
Oh I was using 1.12.2 version of it. I got the 1.8.9 version. It fixed the ERROR: Failed to login to Spotify! Thank you so much!
