### ISSUE TITLE
INVALID_CLIENT: Invalid client

### ISSUE THREAD

**Issue by BubbaJuice** [MediaModMC/MediaMod#60]
**Describe the bug**
"INVALID_CLIENT: Invalid client" when trying to connect the mod to Spotify.

**To Reproduce**
1. Log onto any Minecraft server.
2. Execute the command "/mm"
3. Click on "Services".
4. Click on "Login to Spotify".
5. The website you are brought to should give you the error.

**Expected behavior**
I expected to see some sort of login or verification page to Spotify 

**Screenshots**
Screenshot of error: [https://imgur.com/a/lVjnlsa](https://imgur.com/a/lVjnlsa)

**Operating System**
I am using Linux.

**Service causing this bug, if applicable**
I was using Spotify.

**Additional context**
I tried using Chrome and Firefox, same error.

**Comment by dreamhopping** [comment]
Fixed in 2.0.0-beta.6
