### ISSUE TITLE
MediaMod API refuses to connect even after multiple restarts

### ISSUE THREAD

**Issue by itsDeflex** [MediaModMC/MediaMod#61]
**Describe the bug**
MediaMod API refuses to connect even after multiple restarts

**To Reproduce**
1. Do /mm
2. Click on 'services'
3. Scroll down to 'reconnect'
4. See how it will say "Failed to connect to MediaMod API!"

**Expected behavior**
I expected it to have something along the lines of "Success!"
![2020-10-06_19 17 49](https://user-images.githubusercontent.com/72476164/95270206-0cf45880-0809-11eb-9ae8-5844772c43b4.png)

**Screenshots**
Look at bottom left of attached screenshot.

**Operating System**
macOS

**Service causing this bug, if applicable**
Soundcloud and YouTube

**Additional context**

**Comment by SpiCy0** [comment]
The API is down, there’s no server too host it

**Comment by dreamhopping** [comment]
Fixed in 2.0.0-beta.6
