### ISSUE TITLE
Foobar2000 Support

### ISSUE THREAD

**Issue by PrincessAkira** [MediaModMC/MediaMod#63]
**Is your feature request related to a problem? Please describe.**
It not

**Describe the solution you'd like**
I would like Support for the Music Player Foobar2000, the same way As Spotify is right now

**Describe alternatives you've considered**
Well the same as in Spotify :D

**Additional context**
Nope

**Comment by dreamhopping** [comment]
This will be resolved in the rewrite with support for MediaMod Addons, this issue will be closed when that is implemented

**Comment by cbyrneee** [comment]
If you would wish to make a MediaMod addon for this, checkout the example workspace for an addon [here](https://github.com/MediaModMC/ExampleAddon-Kotlin). Addons will be made available to all users when v2.0.0 is released, which there is no timeframe for at the moment. I do not use foobar2000 or know how their plugin api works, so I will not be making this addon. If anyone wishes to make it, please do.
