### ISSUE TITLE
How to install and use?

### ISSUE THREAD

**Issue by literallyrice** [MediaModMC/MediaMod#64]
Ok look sorry I'm an idiot but how tf do I use this there's no .jar anywhere and there are no tutorials. It's not on the curseforge or anything :/ The discord invite isn't working either. I've tried everything I know how to do but nothing works. my discord is Goblin#6169 if you would like to help.

**Comment by ChachyDev** [comment]
Join the discord at https://inv.wtf/amber and we can help you out from there :)
